### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by SunYanCN** [ziyin-dl/word-embedding-dimensionality-selection#14]
In code matrix/signal_matrix.py:

 def construct_matrix(self):
        raise NotImplementedError

Is this correct? Is there any problem with this part of the code?

**Comment by zi-yin** [comment]
This is expected. The signal matrix class is abstract, and the actual implementations (LSA_matrix, GloVe_matrix, etc.) will be subclasses which actually implement this member function.
