### ISSUE TITLE
Spectral Estimation

### ISSUE THREAD

**Issue by asadullah797** [ziyin-dl/word-embedding-dimensionality-selection#16]
Great Work!!
I am following this paper and its code and I have a question related to Spectral Estimation. How did you get this formula. The reference you have given from [Chatterjee, 2015], I even could not find it in paper.
Also I want to use NMF(Non-negative matrix factorization) instead of SVD, when I use the spectral estimation formula in the paper, I got all the elements become zero. How could I overcome this issue.
Thanks!

**Comment by ziyin-dl** [comment]
1. This is equivalent to the "symmetric model" in [Chatterjee, 2015]:
 - X (in [Chatterjee, 2015]) = M+N where N is an IID noise matrix. Note E[Xij]=Mij.
 - p=1, meaning every entry of X is observed.
 - η -> 0
Under the three points we recover the 2*\sqrt{n}\sigma threshold for singular values.
Note the following remark in [Chatterjee, 2015]:
"One limitation of USVT is the requirement that the entries should lie in a bounded interval. One may relax this requirement by assuming, for example, that the errors xij −mij are distributed as normal random variables with mean zero and variance σ^2. If σ^2 is known, then I believe that one can modify the USVT algorithm by thresholding at (2 + η)σ√n and obtain the same theorems."

2. I believe you might have used the wrong order for NMF in this case. I think the following procedures are reasonable:
 -  Do the spectral estimation first, on the original matrix (say, calculate SVD(\tilde M)=UDV^T).
 -  Apply the soft thresholding operator t on D, and get the "noise filtered" matrix \hat M= Ut(D)V^T
 -  Do a NMF on \hat M.
In this case the spectral estimation part should be identical.

**Comment by asadullah797** [comment]
Really appreciate your response.
Could you please share me what could be the future work using this paper as baseline.
I want to extend your paper work but I don't know the direction.
Can you please give me some suggestions/feedback.
Thank you

**Comment by ziyin-dl** [comment]
I think one direction is to look at other representation learning schemes
and see if similar principals apply there. For example the intermediate
representation obtained by VAE have a fixed, lower dimensionality, and
there people always choose a random one eg 300. It would be of great value
if we can say something about it.
